// Auto-generated by: npm run db:types
// Run after applying SQL migration to your Supabase project
// Replace this file with the output of: supabase gen types typescript --project-id YOUR_ID

export type Database = {
  // Will be populated by Supabase CLI
};
