// Question pool for /jogo/novo and the result-screen reroll (PlayCTA).
// PG-13 max for the "mild" tier — App Store reviewers reject content
// involving drugs, violence, or sexual material, so we keep "mild" in
// the "everyday awkward" zone.
//
// Brand voice: TikTok-friendly, gen-Z, witty, slightly chaotic.

export const CHALLENGE_QUESTIONS: ReadonlyArray<string> = [
  // Original 15
  "Have you ever lied about reading a book everyone's talking about?",
  "Have you ever pretended to laugh at a joke you didn't get?",
  "Have you ever ghosted someone and then run into them in person?",
  "Did you actually finish the last show you said you finished?",
  "Have you ever lied about being sick to skip something?",
  "Have you ever looked up an ex on social media this week?",
  "Have you ever pretended to know a song while singing along?",
  "Have you ever taken credit for someone else's idea at work or school?",
  "Have you ever lied about how much you spent on something?",
  "Have you ever said \"on my way\" when you hadn't left yet?",
  "Have you ever finished a snack you bought to share, before sharing it?",
  "Have you ever tagged someone in a photo just to make them jealous?",
  "Have you ever lied about your age — to anyone, ever?",
  "Have you ever sent a screenshot of a conversation to a third person today?",
  "Have you ever pretended to like a gift in front of the person who gave it to you?",

  // 85 more "everyday awkward" prompts (PG-13)
  "Have you ever blamed a fart on someone else?",
  "Have you ever pretended to be on the phone to avoid a conversation?",
  "Have you ever liked your own post from a finsta?",
  "Have you ever returned something you'd already used?",
  "Have you ever forgotten someone's name mid-sentence?",
  "Have you ever rehearsed a casual text before sending it?",
  "Have you ever Googled yourself in the last month?",
  "Have you ever cancelled plans the morning of, just because?",
  "Have you ever cried at a Pixar movie in public?",
  "Have you ever lied about going to the gym?",
  "Have you ever told someone you were 5 minutes away when you were 25?",
  "Have you ever taken a photo of food just to post it, then not eaten it warm?",
  "Have you ever slept with the lights on because of a horror movie?",
  "Have you ever pretended your phone died to avoid replying?",
  "Have you ever bought clothes one size smaller as motivation?",
  "Have you ever lied to your dentist about flossing?",
  "Have you ever pretended to be drunker than you actually were?",
  "Have you ever pretended to be more sober than you actually were?",
  "Have you ever fake-laughed at your boss?",
  "Have you ever skipped a chapter of a book and pretended you read it?",
  "Have you ever stayed in bed past 2pm on a weekday with no reason?",
  "Have you ever sent a text to the wrong person and instantly panicked?",
  "Have you ever screen-recorded a conversation?",
  "Have you ever stalked a stranger's Instagram for over an hour?",
  "Have you ever made up a quote and attributed it to someone famous?",
  "Have you ever taken the last slice and lied about it?",
  "Have you ever pretended a song was your favorite to impress someone?",
  "Have you ever cried, then immediately checked yourself in the mirror?",
  "Have you ever forwarded a meme as if you made it?",
  "Have you ever lied about your zodiac sign?",
  "Have you ever pretended to be allergic to skip a food?",
  "Have you ever texted while pretending to listen?",
  "Have you ever told a server it was your birthday when it wasn't?",
  "Have you ever lied about who you voted for?",
  "Have you ever pretended your Wi-Fi was bad to leave a Zoom?",
  "Have you ever used someone else's Netflix without telling them?",
  "Have you ever returned a plant to the store after it died on you?",
  "Have you ever lied about your steps count for the day?",
  "Have you ever picked a fight to avoid talking about feelings?",
  "Have you ever put on perfume instead of showering?",
  "Have you ever re-gifted something to the person who gave it to you?",
  "Have you ever pretended to have read someone's text before they asked?",
  "Have you ever bought a self-help book and never opened it?",
  "Have you ever lied about how many people you've kissed?",
  "Have you ever judged someone's outfit and then bought the same thing?",
  "Have you ever faked enthusiasm for a baby photo?",
  "Have you ever pretended to be vegan for one date?",
  "Have you ever rage-quit a group chat then asked to be added back?",
  "Have you ever given a fake number?",
  "Have you ever followed your ex's new partner on social media?",
  "Have you ever screenshotted a friend's text just to send it elsewhere?",
  "Have you ever ducked into a store to avoid someone you saw on the street?",
  "Have you ever lied about loving the gift just to be polite?",
  "Have you ever cried in an Uber?",
  "Have you ever pretended a typo was on purpose?",
  "Have you ever started a podcast in your head and never recorded it?",
  "Have you ever blamed a delay on traffic when you slept in?",
  "Have you ever lied about how spicy you can handle food?",
  "Have you ever sent a 'wyd' just to see who'd reply?",
  "Have you ever added someone on LinkedIn out of pure curiosity?",
  "Have you ever pretended to be on hold to skip a call?",
  "Have you ever said a movie was great when you actually slept through it?",
  "Have you ever taken the AirPods out only to nod along?",
  "Have you ever changed your accent around someone you're attracted to?",
  "Have you ever pretended to be older to get into a place?",
  "Have you ever bought a pricey latte and then snapped it for the gram?",
  "Have you ever sent an email and then regretted it instantly?",
  "Have you ever said 'I'll think about it' meaning a hard no?",
  "Have you ever lied about being a morning person?",
  "Have you ever pretended to know the rules of a card game?",
  "Have you ever started crying at a song in public?",
  "Have you ever told a friend you 'haven't seen the message' when you had?",
  "Have you ever tried on clothes in a store and forgotten to put them back?",
  "Have you ever cooked something, called it 'fine,' and then ordered takeout?",
  "Have you ever lied about doing your skincare routine?",
  "Have you ever pretended you forgot your wallet when you didn't?",
  "Have you ever used your dog/cat to get out of socializing?",
  "Have you ever told a kid Santa was real way past the age you should have?",
  "Have you ever pretended to hate a band you secretly love?",
  "Have you ever changed the song you were vibing to when someone walked in?",
  "Have you ever lied about having seen a 'classic' movie?",
  "Have you ever called shotgun to avoid sitting next to someone specific?",
  "Have you ever lied about your tattoo's meaning?",
  "Have you ever taken a 'just looking' five-minute walk through Sephora?",
  "Have you ever pretended to be lost just to start a conversation?",
  "Have you ever liked someone's old post by accident?",
  "Have you ever blamed Wi-Fi for a missed deadline?",
  "Have you ever pretended to be sober enough to drive home?",
  "Have you ever rehearsed an apology in the mirror?",
];

export function pickRandomQuestion(exclude?: string): string {
  const pool = exclude
    ? CHALLENGE_QUESTIONS.filter((q) => q !== exclude)
    : CHALLENGE_QUESTIONS;
  const i = Math.floor(Math.random() * pool.length);
  return pool[i];
}

export function questionAt(index: number): string {
  return CHALLENGE_QUESTIONS[index % CHALLENGE_QUESTIONS.length];
}
