// Question pool for /jogo/novo and the result-screen reroll (PlayCTA).
// PG-13 max for the "mild" tier — App Store reviewers reject content
// involving drugs, violence, or sexual material, so we keep "mild" in
// the "everyday awkward" zone.
//
// Brand voice: TikTok-friendly, gen-Z, witty, slightly chaotic.

export const CHALLENGE_QUESTIONS: ReadonlyArray<string> = [
  // Original 15
  "Have you ever lied about reading a book everyone's talking about?",
  "Have you ever pretended to laugh at a joke you didn't get?",
  "Have you ever ghosted someone and then run into them in person?",
  "Did you actually finish the last show you said you finished?",
  "Have you ever lied about being sick to skip something?",
  "Have you ever looked up an ex on social media this week?",
  "Have you ever pretended to know a song while singing along?",
  "Have you ever taken credit for someone else's idea at work or school?",
  "Have you ever lied about how much you spent on something?",
  "Have you ever said \"on my way\" when you hadn't left yet?",
  "Have you ever finished a snack you bought to share, before sharing it?",
  "Have you ever tagged someone in a photo just to make them jealous?",
  "Have you ever lied about your age — to anyone, ever?",
  "Have you ever sent a screenshot of a conversation to a third person today?",
  "Have you ever pretended to like a gift in front of the person who gave it to you?",

  // 85 more "everyday awkward" prompts (PG-13)
  "Have you ever blamed a fart on someone else?",
  "Have you ever pretended to be on the phone to avoid a conversation?",
  "Have you ever liked your own post from a finsta?",
  "Have you ever returned something you'd already used?",
  "Have you ever forgotten someone's name mid-sentence?",
  "Have you ever rehearsed a casual text before sending it?",
  "Have you ever Googled yourself in the last month?",
  "Have you ever cancelled plans the morning of, just because?",
  "Have you ever cried at a Pixar movie in public?",
  "Have you ever lied about going to the gym?",
  "Have you ever told someone you were 5 minutes away when you were 25?",
  "Have you ever taken a photo of food just to post it, then not eaten it warm?",
  "Have you ever slept with the lights on because of a horror movie?",
  "Have you ever pretended your phone died to avoid replying?",
  "Have you ever bought clothes one size smaller as motivation?",
  "Have you ever lied to your dentist about flossing?",
  "Have you ever pretended to be drunker than you actually were?",
  "Have you ever pretended to be more sober than you actually were?",
  "Have you ever fake-laughed at your boss?",
  "Have you ever skipped a chapter of a book and pretended you read it?",
  "Have you ever stayed in bed past 2pm on a weekday with no reason?",
  "Have you ever sent a text to the wrong person and instantly panicked?",
  "Have you ever screen-recorded a conversation?",
  "Have you ever stalked a stranger's Instagram for over an hour?",
  "Have you ever made up a quote and attributed it to someone famous?",
  "Have you ever taken the last slice and lied about it?",
  "Have you ever pretended a song was your favorite to impress someone?",
  "Have you ever cried, then immediately checked yourself in the mirror?",
  "Have you ever forwarded a meme as if you made it?",
  "Have you ever lied about your zodiac sign?",
  "Have you ever pretended to be allergic to skip a food?",
  "Have you ever texted while pretending to listen?",
  "Have you ever told a server it was your birthday when it wasn't?",
  "Have you ever lied about who you voted for?",
  "Have you ever pretended your Wi-Fi was bad to leave a Zoom?",
  "Have you ever used someone else's Netflix without telling them?",
  "Have you ever returned a plant to the store after it died on you?",
  "Have you ever lied about your steps count for the day?",
  "Have you ever picked a fight to avoid talking about feelings?",
  "Have you ever put on perfume instead of showering?",
  "Have you ever re-gifted something to the person who gave it to you?",
  "Have you ever pretended to have read someone's text before they asked?",
  "Have you ever bought a self-help book and never opened it?",
  "Have you ever lied about how many people you've kissed?",
  "Have you ever judged someone's outfit and then bought the same thing?",
  "Have you ever faked enthusiasm for a baby photo?",
  "Have you ever pretended to be vegan for one date?",
  "Have you ever rage-quit a group chat then asked to be added back?",
  "Have you ever given a fake number?",
  "Have you ever followed your ex's new partner on social media?",
  "Have you ever screenshotted a friend's text just to send it elsewhere?",
  "Have you ever ducked into a store to avoid someone you saw on the street?",
  "Have you ever lied about loving the gift just to be polite?",
  "Have you ever cried in an Uber?",
  "Have you ever pretended a typo was on purpose?",
  "Have you ever started a podcast in your head and never recorded it?",
  "Have you ever blamed a delay on traffic when you slept in?",
  "Have you ever lied about how spicy you can handle food?",
  "Have you ever sent a 'wyd' just to see who'd reply?",
  "Have you ever added someone on LinkedIn out of pure curiosity?",
  "Have you ever pretended to be on hold to skip a call?",
  "Have you ever said a movie was great when you actually slept through it?",
  "Have you ever taken the AirPods out only to nod along?",
  "Have you ever changed your accent around someone you're attracted to?",
  "Have you ever pretended to be older to get into a place?",
  "Have you ever bought a pricey latte and then snapped it for the gram?",
  "Have you ever sent an email and then regretted it instantly?",
  "Have you ever said 'I'll think about it' meaning a hard no?",
  "Have you ever lied about being a morning person?",
  "Have you ever pretended to know the rules of a card game?",
  "Have you ever started crying at a song in public?",
  "Have you ever told a friend you 'haven't seen the message' when you had?",
  "Have you ever tried on clothes in a store and forgotten to put them back?",
  "Have you ever cooked something, called it 'fine,' and then ordered takeout?",
  "Have you ever lied about doing your skincare routine?",
  "Have you ever pretended you forgot your wallet when you didn't?",
  "Have you ever used your dog/cat to get out of socializing?",
  "Have you ever told a kid Santa was real way past the age you should have?",
  "Have you ever pretended to hate a band you secretly love?",
  "Have you ever changed the song you were vibing to when someone walked in?",
  "Have you ever lied about having seen a 'classic' movie?",
  "Have you ever called shotgun to avoid sitting next to someone specific?",
  "Have you ever lied about your tattoo's meaning?",
  "Have you ever taken a 'just looking' five-minute walk through Sephora?",
  "Have you ever pretended to be lost just to start a conversation?",
  "Have you ever liked someone's old post by accident?",
  "Have you ever blamed Wi-Fi for a missed deadline?",
  "Have you ever pretended to be sober enough to drive home?",
  "Have you ever rehearsed an apology in the mirror?",

  // ─── Wave 2: 150 more (still PG-13, "everyday awkward") ───────────────
  "Have you ever sent a heart emoji to the wrong person?",
  "Have you ever pretended a podcast was your favorite to seem smart?",
  "Have you ever asked someone to take a photo of you 'casually'?",
  "Have you ever stalked a wedding registry of someone you barely know?",
  "Have you ever pre-stalked a brunch menu the night before?",
  "Have you ever Googled a friend's salary range?",
  "Have you ever pretended to be allergic to skip a dish?",
  "Have you ever told someone a movie was 'a classic' to dodge admitting you hadn't seen it?",
  "Have you ever lied about how often you do laundry?",
  "Have you ever pretended to know the lyrics to your own karaoke pick?",
  "Have you ever practiced your laugh in the mirror?",
  "Have you ever told someone your tattoo had deep meaning when it didn't?",
  "Have you ever blamed a missed deadline on Wi-Fi?",
  "Have you ever pretended to run into someone 'by chance'?",
  "Have you ever gone to a party uninvited and acted like you belonged?",
  "Have you ever stayed at a job you hated just for the title?",
  "Have you ever lied about your age to a fitness instructor?",
  "Have you ever done a victory dance after winning a small argument?",
  "Have you ever pretended to enjoy a podcast just to fit in?",
  "Have you ever told a partner their cooking was great when it really wasn't?",
  "Have you ever started a 'self-care Sunday' and given up by 11am?",
  "Have you ever hate-watched something you'd publicly insult?",
  "Have you ever pretended you weren't drunk in front of an Uber driver?",
  "Have you ever rehearsed how you'd react to a surprise?",
  "Have you ever tagged someone in a photo just to make them mad?",
  "Have you ever rated a date out of 10 in your Notes app?",
  "Have you ever pretended a song was your favorite to impress someone?",
  "Have you ever taken a 'just looking' lap through a luxury store?",
  "Have you ever told someone you were 'almost there' from your couch?",
  "Have you ever lied about how long you've been single?",
  "Have you ever lied about your coffee order to seem fancier?",
  "Have you ever made a dramatic exit no one noticed?",
  "Have you ever told a server 'no rush' and immediately stared at the kitchen?",
  "Have you ever pretended to know a celebrity's whole career?",
  "Have you ever lied about the last book you read?",
  "Have you ever pretended you knew how to use chopsticks?",
  "Have you ever reposted someone's tweet as if you wrote it?",
  "Have you ever made a fake phone call to leave a bad date?",
  "Have you ever lied about your zodiac to avoid a conversation?",
  "Have you ever pretended to be a couple with a friend to dodge a creep?",
  "Have you ever lied about being 'almost done' on a project?",
  "Have you ever blamed traffic when there literally wasn't any?",
  "Have you ever clapped at a movie ending no one else liked?",
  "Have you ever lied about your real opinion on a friend's haircut?",
  "Have you ever pretended to enjoy hosting a party?",
  "Have you ever told a friend you 'loved' a place you actively hated?",
  "Have you ever lied about not having a dating app?",
  "Have you ever sent a 'you up?' text strictly out of boredom?",
  "Have you ever blocked someone, then unblocked, then blocked again?",
  "Have you ever pretended to be sick to leave brunch?",
  "Have you ever taken credit for a recipe you Googled mid-cook?",
  "Have you ever judged someone's playlist and then saved it?",
  "Have you ever forgotten you muted yourself and ranted on a video call?",
  "Have you ever made a finsta to follow your friends without them knowing?",
  "Have you ever practiced an Oscar speech in the shower?",
  "Have you ever cried at a Taylor Swift bridge in public?",
  "Have you ever liked someone's ancient post and immediately panicked?",
  "Have you ever pretended a typo was on purpose to be cute?",
  "Have you ever bragged about something you didn't really do?",
  "Have you ever told a kid the toy was 'broken' just to end playtime?",
  "Have you ever lied about how many cookies you ate?",
  "Have you ever pretended your dog was a service dog to bring it inside?",
  "Have you ever screenshot a friend's text just to read it later?",
  "Have you ever told your group you couldn't drink, then sipped your friend's drink?",
  "Have you ever lied about a hobby on a dating app?",
  "Have you ever told a date your job was cooler than it is?",
  "Have you ever stalked a stranger's LinkedIn for fun?",
  "Have you ever pretended to like a band to fit in with new friends?",
  "Have you ever lied about how 'fine' you were after a breakup?",
  "Have you ever pretended to have read a book you only watched a YouTube essay about?",
  "Have you ever stayed at a party past comfort just to not be the first to leave?",
  "Have you ever scrolled past a mutual's life update without congratulating them?",
  "Have you ever lied about why you were late?",
  "Have you ever pretended to enjoy a homemade gift?",
  "Have you ever taken the long way home to dodge a neighbor?",
  "Have you ever pretended you were 'almost ready' in pajamas?",
  "Have you ever made a TikTok and immediately deleted it?",
  "Have you ever pretended your phone was on Do Not Disturb?",
  "Have you ever lied about your phone being old to dodge a video call?",
  "Have you ever talked smack about your job in an Uber by accident?",
  "Have you ever practiced texting an ex without sending it?",
  "Have you ever lied about how often you check on your plants?",
  "Have you ever made up a quote and credited it to a famous person?",
  "Have you ever pretended your AirPods were the reason you ignored someone?",
  "Have you ever sent the same compliment to multiple people in one day?",
  "Have you ever lied about being 'too tired' just to be alone?",
  "Have you ever told a friend their playlist was great and meant it?",
  "Have you ever taken the AirPods out only to nod and pretend you heard everything?",
  "Have you ever pretended to enjoy meeting a partner's parents?",
  "Have you ever pretended to be okay with the chore split?",
  "Have you ever blamed Mercury retrograde for a bad mood?",
  "Have you ever lied about how often you skip the gym?",
  "Have you ever pre-shopped a sale and lied that you 'just stumbled in'?",
  "Have you ever lied about loving the haircut you really hated?",
  "Have you ever started a podcast in your head and quit by episode 2?",
  "Have you ever lied about your favorite movie to seem more interesting?",
  "Have you ever taken a 'casual' selfie that took 12 minutes to set up?",
  "Have you ever sent a lengthy voice note and prayed they wouldn't reply?",
  "Have you ever pretended to be more tipsy to skip a hard conversation?",
  "Have you ever blamed your roommate for things you did?",
  "Have you ever lied about your high school superlative?",
  "Have you ever pretended you didn't see someone wave at you?",
  "Have you ever lied about how often you make your bed?",
  "Have you ever told someone they 'deserved better' while secretly meaning yourself?",
  "Have you ever pretended to be a morning person on date 3?",
  "Have you ever smiled politely at a kid screaming in a restaurant?",
  "Have you ever lied about being the 'designated driver'?",
  "Have you ever lied about reading the group chat backlog?",
  "Have you ever pretended your group chat was 'so funny' when it was just chaos?",
  "Have you ever lied about your favorite emoji?",
  "Have you ever blamed your partner for something the cat did?",
  "Have you ever pretended a coworker's joke was funny in front of HR?",
  "Have you ever ghosted someone, then liked their post months later?",
  "Have you ever pretended your coffee was decaf to dodge a 9pm conversation?",
  "Have you ever lied about being on a 'no-spend' month?",
  "Have you ever lied about doing a yoga 'practice' at home?",
  "Have you ever lied about a 'family emergency' to leave a party early?",
  "Have you ever taken a flu day for a personal day?",
  "Have you ever pretended you were 'almost out the door' from your bed?",
  "Have you ever judged a coworker's email signature out loud?",
  "Have you ever lied about the last show you binged?",
  "Have you ever pretended to enjoy a sport just to date someone?",
  "Have you ever taken a 'business call' to avoid a roommate?",
  "Have you ever lied about already having plans?",
  "Have you ever pretended your group needed to leave 'now' to break a hangout?",
  "Have you ever pre-Googled a restaurant menu so you'd order 'spontaneously'?",
  "Have you ever lied about loving a niche movie just to seem cultured?",
  "Have you ever exited a Zoom by faking a frozen screen?",
  "Have you ever stood up a friend by pretending to be sick?",
  "Have you ever used 'k.' as a passive-aggressive weapon?",
  "Have you ever lied about how many seasons of a show you've watched?",
  "Have you ever pretended your sister/brother was the family villain?",
  "Have you ever told a story as 'something that happened to a friend'?",
  "Have you ever pretended you were the Aux master while panic-Googling songs?",
  "Have you ever lied to a hairdresser about how much you'd care if it went wrong?",
  "Have you ever lied about a 'spa day' that was just a long shower?",
  "Have you ever lied about being 'mid-task' to dodge a quick favor?",
  "Have you ever pretended to be at the gym while parked outside it?",
  "Have you ever lied about an Amazon delivery being 'lost'?",
  "Have you ever lied about how you got home from a night out?",
  "Have you ever lied about the cost of a haircut?",
  "Have you ever lied about your favorite drink to avoid being teased?",
  "Have you ever blamed Wi-Fi to leave a meeting you were enjoying?",
  "Have you ever pretended to be on a 'cleanse' to skip a snack?",
  "Have you ever lied about how good your sleep schedule is?",
  "Have you ever told a friend you didn't see their text for 3 days when you saw it in 3 minutes?",
  "Have you ever lied about how many kids' birthdays you remember?",
  "Have you ever lied about loving a wedding you secretly hated?",
  "Have you ever lied about who picked the restaurant?",
  "Have you ever pretended to be 'over' someone you saw at a party?",
];

export function pickRandomQuestion(exclude?: string): string {
  const pool = exclude
    ? CHALLENGE_QUESTIONS.filter((q) => q !== exclude)
    : CHALLENGE_QUESTIONS;
  const i = Math.floor(Math.random() * pool.length);
  return pool[i];
}

export function questionAt(index: number): string {
  return CHALLENGE_QUESTIONS[index % CHALLENGE_QUESTIONS.length];
}
